# Generated by Django 4.2.2 on 2023-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='login_requier',
            field=models.BooleanField(default=False),
        ),
    ]
