# Generated by Django 4.2.2 on 2023-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_login_requier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_requier',
        ),
        migrations.AddField(
            model_name='post',
            name='login_requier',
            field=models.BooleanField(default=False),
        ),
    ]
